### PR TITLE
Add GitHub starter workflow

### PR DESCRIPTION
**Pull request by emcfarlane**
Add the default buf-ci.yaml workflow as a starter workflow. See: https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization

### CODE REVIEW

**Comment by nicksnyder** [comment]
Does checking this in actually make this work somewhere? By my reading of the docs you linked, for a user to take advantage of these files, they need to create a `.github` repository in their organization and copy these files there. Do you have a different understanding?

If I am correct, it seems like we actually want is documentation how to do that rather than just checking in these files.

**Comment by emcfarlane** [comment]
It should become part of the workflow templates on clicking new workflow in the GitHub actions UI: https://github.com/bufbuild/buf-action/actions/new
I'm not sure if it's available outside of the buf org, that may require some manual step from GitHub.

**Comment by nicksnyder** [comment]
Can you please research this a bit more, and verify what actually needs to happen to make this work? Everything I can find points to this will not work as is.

1. The docs clearly state that if you want to share a workflow within an organization, it needs to defined inside of a `.github` repository (not in a `.github/` directory inside of a GitHub action).
> Starter workflows can be created by users with write access to the organization's public .github repository. These can then be used by organization members who have permission to create workflows.

2. It seems like this is the repo you would need to submit a PR to if you want this to appear to other orgs: https://github.com/actions/starter-workflows

**Comment by emcfarlane** [comment]
Sorry, this was my misunderstanding. Closing needs more research.

**Pull request closed without merging**
